-- VELTIER Supabase setup
-- Supabase SQL Editor에서 한 번 실행하세요.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null,
  phone text default '',
  role text not null default 'customer' check (role in ('customer', 'admin', 'manager')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists role text not null default 'customer';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
  ) then
    alter table public.profiles
    add constraint profiles_role_check check (role in ('customer', 'admin', 'manager'));
  end if;
end $$;

create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_index integer not null,
  product_name text not null,
  product_image text default '',
  price numeric not null default 0,
  device text not null,
  quantity integer not null default 1 check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_index, device)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  product_index integer not null unique,
  name text not null,
  material text not null default '',
  color text not null default '#202124',
  price numeric not null default 0 check (price >= 0),
  media_type text not null default 'image' check (media_type in ('image', 'video')),
  image text default '',
  video text default '',
  show_in_hero boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_index integer not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  author text not null,
  rating integer not null check (rating between 1 and 5),
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('VT-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending_payment' check (status in ('pending_payment', 'paid', 'preparing', 'shipped', 'delivered', 'cancelled')),
  payment_status text not null default 'not_started' check (payment_status in ('not_started', 'ready', 'paid', 'failed', 'cancelled', 'refunded')),
  recipient_name text not null,
  phone text not null,
  email text not null,
  postal_code text default '',
  address1 text not null,
  address2 text default '',
  delivery_note text default '',
  subtotal numeric not null default 0 check (subtotal >= 0),
  shipping_fee numeric not null default 0 check (shipping_fee >= 0),
  total numeric not null default 0 check (total >= 0),
  currency text not null default 'KRW',
  payment_provider text default '',
  provider_payment_id text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_index integer not null,
  product_name text not null,
  product_image text default '',
  device text not null,
  quantity integer not null default 1 check (quantity > 0),
  price numeric not null default 0 check (price >= 0),
  line_total numeric not null default 0 check (line_total >= 0),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.cart_items enable row level security;
alter table public.products enable row level security;
alter table public.reviews enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

create or replace function public.keep_profile_role_safe()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.role is distinct from new.role and not public.is_admin() then
    new.role = old.role;
  end if;
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists protect_profile_role on public.profiles;
create trigger protect_profile_role
before update on public.profiles
for each row execute function public.keep_profile_role_safe();

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_products_updated_at on public.products;
create trigger touch_products_updated_at
before update on public.products
for each row execute function public.touch_updated_at();

drop trigger if exists touch_orders_updated_at on public.orders;
create trigger touch_orders_updated_at
before update on public.orders
for each row execute function public.touch_updated_at();

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "cart_items_manage_own" on public.cart_items;
create policy "cart_items_manage_own"
on public.cart_items for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "products_select_public_active" on public.products;
create policy "products_select_public_active"
on public.products for select
using (is_active = true or public.is_admin());

drop policy if exists "products_admin_manage" on public.products;
create policy "products_admin_manage"
on public.products for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "reviews_select_public" on public.reviews;
create policy "reviews_select_public"
on public.reviews for select
using (true);

drop policy if exists "reviews_insert_auth" on public.reviews;
create policy "reviews_insert_auth"
on public.reviews for insert
with check (auth.uid() = user_id);

drop policy if exists "reviews_update_own" on public.reviews;
create policy "reviews_update_own"
on public.reviews for update
using (auth.uid() = user_id or public.is_admin())
with check (auth.uid() = user_id or public.is_admin());

drop policy if exists "reviews_delete_own" on public.reviews;
create policy "reviews_delete_own"
on public.reviews for delete
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "orders_select_own_or_admin" on public.orders;
create policy "orders_select_own_or_admin"
on public.orders for select
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "orders_insert_own" on public.orders;
create policy "orders_insert_own"
on public.orders for insert
with check (auth.uid() = user_id);

drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update"
on public.orders for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "order_items_select_own_or_admin" on public.order_items;
create policy "order_items_select_own_or_admin"
on public.order_items for select
using (
  public.is_admin()
  or exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

drop policy if exists "order_items_insert_own_order" on public.order_items;
create policy "order_items_insert_own_order"
on public.order_items for insert
with check (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
  )
);

drop policy if exists "order_items_admin_manage" on public.order_items;
create policy "order_items_admin_manage"
on public.order_items for all
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (id, name, public)
values ('product-media', 'product-media', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "product_media_public_read" on storage.objects;
create policy "product_media_public_read"
on storage.objects for select
using (bucket_id = 'product-media');

drop policy if exists "product_media_admin_insert" on storage.objects;
create policy "product_media_admin_insert"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-media' and public.is_admin());

drop policy if exists "product_media_admin_update" on storage.objects;
create policy "product_media_admin_update"
on storage.objects for update
to authenticated
using (bucket_id = 'product-media' and public.is_admin())
with check (bucket_id = 'product-media' and public.is_admin());

drop policy if exists "product_media_admin_delete" on storage.objects;
create policy "product_media_admin_delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-media' and public.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, name, phone, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'phone', ''),
    'customer'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    name = excluded.name,
    phone = excluded.phone,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.reviews (product_index, user_id, author, rating, title, body)
select 0, id, '민서', 5, '흰 배경에서도 존재감이 좋아요', '아이보리 톤이 너무 밝게 날리지 않고 골드 링이 은은해서 실제로 고급스러워 보입니다.'
from auth.users
limit 1
on conflict do nothing;

-- 첫 관리자 지정은 회원가입 후 이메일을 바꿔서 한 번만 실행하세요.
-- update public.profiles set role = 'admin' where email = 'owner@example.com';

-- Commerce operations extension: order management, product inventory, and email notification queue.

alter table public.orders
  add column if not exists tracking_number text default '',
  add column if not exists tracking_url text default '',
  add column if not exists admin_note text default '',
  add column if not exists paid_at timestamptz,
  add column if not exists shipped_at timestamptz;

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_index integer not null,
  device text not null,
  sku text default '',
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  low_stock_threshold integer not null default 3 check (low_stock_threshold >= 0),
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_index, device)
);

create table if not exists public.notification_events (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  recipient_email text not null,
  subject text not null,
  body text not null,
  status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'skipped')),
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create table if not exists public.user_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default '기본 배송지',
  recipient_name text not null,
  phone text not null,
  postal_code text default '',
  address1 text not null,
  address2 text default '',
  delivery_note text default '',
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_variants enable row level security;
alter table public.notification_events enable row level security;
alter table public.user_addresses enable row level security;

drop trigger if exists touch_product_variants_updated_at on public.product_variants;
create trigger touch_product_variants_updated_at
before update on public.product_variants
for each row execute function public.touch_updated_at();

drop trigger if exists touch_user_addresses_updated_at on public.user_addresses;
create trigger touch_user_addresses_updated_at
before update on public.user_addresses
for each row execute function public.touch_updated_at();

drop policy if exists "product_variants_select_public" on public.product_variants;
create policy "product_variants_select_public"
on public.product_variants for select
using (true);

drop policy if exists "product_variants_admin_manage" on public.product_variants;
create policy "product_variants_admin_manage"
on public.product_variants for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "notification_events_select_own_or_admin" on public.notification_events;
create policy "notification_events_select_own_or_admin"
on public.notification_events for select
using (public.is_admin() or user_id = auth.uid());

drop policy if exists "notification_events_insert_own_or_admin" on public.notification_events;
create policy "notification_events_insert_own_or_admin"
on public.notification_events for insert
with check (public.is_admin() or user_id = auth.uid());

drop policy if exists "notification_events_admin_update" on public.notification_events;
create policy "notification_events_admin_update"
on public.notification_events for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "notification_events_admin_delete" on public.notification_events;
create policy "notification_events_admin_delete"
on public.notification_events for delete
using (public.is_admin());

drop policy if exists "user_addresses_manage_own" on public.user_addresses;
create policy "user_addresses_manage_own"
on public.user_addresses for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

insert into public.product_variants (
  product_index,
  device,
  sku,
  stock_quantity,
  low_stock_threshold,
  is_available
)
select
  products.product_index,
  devices.device,
  'VT-' || lpad((products.product_index + 1)::text, 3, '0') || '-' || regexp_replace(upper(devices.device), '[^A-Z0-9]', '', 'g'),
  12,
  3,
  products.is_active
from public.products
cross join (
  values
    ('iPhone 16 Pro'),
    ('iPhone 16'),
    ('iPhone 15 Pro'),
    ('iPhone 15'),
    ('iPhone 14 Pro'),
    ('iPhone 14'),
    ('Galaxy S25'),
    ('Galaxy S24')
) as devices(device)
on conflict (product_index, device) do nothing;
